file:C:/Program Files/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig	http.sslbackend=schannel
file:C:/Program Files/Git/etc/gitconfig	core.autocrlf=true
file:C:/Program Files/Git/etc/gitconfig	core.fscache=true
file:C:/Program Files/Git/etc/gitconfig	core.symlinks=false
file:C:/Program Files/Git/etc/gitconfig	pull.rebase=false
file:C:/Program Files/Git/etc/gitconfig	credential.helper=manager
file:C:/Program Files/Git/etc/gitconfig	credential.https://dev.azure.com.usehttppath=true
file:C:/Program Files/Git/etc/gitconfig	init.defaultbranch=master
file:C:/Users/ATVIK SHARMA/.gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/ATVIK SHARMA/.gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/ATVIK SHARMA/.gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Users/ATVIK SHARMA/.gitconfig	filter.lfs.required=true
file:C:/Users/ATVIK SHARMA/.gitconfig	user.name=amit-sharma-ds
file:C:/Users/ATVIK SHARMA/.gitconfig	user.email=amsharma2607@gmai.com
file:C:/Users/ATVIK SHARMA/.gitconfig	credential.helper=manager
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	lfs.repositoryformatversion=0
file:.git/config	remote.origin.url=https://github.com/amit-sharma-ds/GenAIDoctor.git
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config	branch.main.vscode-merge-base=origin/main
